### ISSUE TITLE
Compensate feedback loop

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-soyosource-gtn-virtual-meter#4]
1. The power demand is 100W
2. The virtual meter requests 100W -> the inverter provides 100W -> the power demand is 0W
3. The virtual meter requests 0W because the power demand is 0W
4. The power demand is 100W because the inverter provides 0W (goto 1)

**Comment by ChrisHomewood** [comment]
Thanks for integrating the code :)

Incidentally your code mimics what the meter supplied with the inverter does, it cannot sense direction of current flow so always outputs a positive value. This is why in the instruction manual the inverter is to be wired in-front of the load with the meter behind the inverter but in front of the load, this way the meter can measure the load the inverter has to match without being effected by the inverter output. This makes design of the meter super simple but doesn't reflect the way most people will wire this inverter as it is typically very difficult to wire it in between the fuse box and the supply meter.

So if you are using a meter input that is effected by the inverter (e.g. you are using your utility meter as a data source and the inverter is wired into an existing household circuit (via a plug socket, etc)) what you need is inverter control that always attempts to get the meter to read zero, which is what my code does, but it requires a meter that can measure direction of current flow (i.e. go negative). It just adds the meter reading minus buffer to the current inverter output so it will naturally chase itself to near zero.

You could improve the code by having it change faster if there is a large difference in meter reading but in reality I found it followed the load close enough for my purposes and never bothered doing anything fancy.

I wouldn't recommend using the output reported by the inverter as part of the calculation because that is not very accurate (and I think its flow from the battery so includes inverter efficiency losses), just stick with the previous demand request and assume the inverter will follow the demand.
